---
- name: Sichere NEXen
  hosts: nex
  connection: network_cli
  ansible_network_os: nxos
  gather_facts: no
  tasks:
    - ios_command:
        commands: show run
      register: show_run
    - copy:
        content: "{{ show_run.stdout[0] }}"
        dest: "/etc/ansible/backups/{{ inventory_hostname }}.txt"
